### ISSUE TITLE
Kernel with TE0820 (Zynq Ultrascale +). 

### ISSUE THREAD

**Issue by timoteogb** [SundanceMultiprocessorTechnology/VCS-1_FM191_FW#4] opened 2018-06-27 15:07 UTC
I'm trying to test the USB3. Please, the file system is not recognized. I followed the same steps described for Zynq 7000, changing:

+ zynqMP instead of zynq when creating a Petalinux project
+ added --pmufw when generating the BOOT.BIN, to fetch pmufw.elf
+ when configuring the kernel, I added all the USB requirements described here: https://medium.com/developments-and-implementations-on-zynq-7000-ap/interfacing-a-usb-webcam-and-enable-usb-tethering-on-zynq-7000-ap-soc-running-linux-1ba6d836749d

```
timin@timin:~$ minicom -D /dev/ttyUSB0

Welcome to minicom 2.7.1

OPTIONS: I18n 
Compiled on Aug 13 2017, 15:25:34.
Port /dev/ttyUSB0, 16:01:05

Press CTRL-A Z for help on special keys



U-Boot 2017.01 (Jun 27 2018 - 15:52:55 +0100) Xilinx ZynqMP ZCU102 revB

I2C:   ready
DRAM:  1 GiB
ERROR: usb dr_mode not found

at /media/timin/TUSB/Petalinux_projects/USB3TEST/build/tmp/work/plnx_aarch64-xi)
EL Level:       EL2
Chip ID:        xczu3eg
MMC:   sdhci@ff160000: 0 (eMMC), sdhci@ff170000: 1 (SD)
zynqmp_qspi_ofdata_to_platdata: CLK 299999961
SF: Detected n25q256a with page size 512 Bytes, erase size 128 KiB, total 64 MiB
*** Warning - bad CRC, using default environment                                
                                                                                
In:    serial                                                                   
Out:   serial                                                                   
Err:   serial                                                                   
Bootmode: SD_MODE1                                                              
Net:   ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                 
PHY is not detected                                                             
GEM PHY init failed                                                             
No ethernet found.                                                              
U-BOOT for USB3TEST                                                             
                                                                                
ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                        
mdio_register: non unique device name 'eth0'                                    
ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                        
mdio_register: non unique device name 'eth0'                                    
ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                        
mdio_register: non unique device name 'eth0'                                    
ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                        
mdio_register: non unique device name 'eth0'                                    
No ethernet found.                                                              
ZYNQ GEM: ff0e0000, phyaddr ffffffff, interface rgmii-id                        
mdio_register: non unique device name 'eth0'                                    
Hit any key to stop autoboot:  0                                                
Failed to mount ext2 filesystem...                                              
** Unrecognized filesystem type **                                              
Device: sdhci@ff160000                                                          
Manufacturer ID: 13                                                             
OEM: 14e                                                                        
Name: Q2J54                                                                     
Tran Speed: 200000000                                                           
Rd Block Len: 512                                                               
MMC version 5.0                                                                 
High Capacity: Yes                                                              
Capacity: 3.6 GiB                                                               
Bus Width: 8-bit                                                                
Erase Group Size: 512 KiB                                                       
HC WP Group Size: 8 MiB                                                         
User Capacity: 3.6 GiB WRREL                                                    
Boot Capacity: 16 MiB ENH                                                       
RPMB Capacity: 512 KiB ENH                                                      
** Unrecognized filesystem type **                                              
ZynqMP> 
```

**Comment by Pranjali-Shinde** [comment] 2018-07-17 15:34
Hi @PedroSundance 
Sorry for the delayed response. The model on which I am working is TE0715-04-30-1C Zynq Z7030 board. I have generated the Petalinux kernel with Linux running on the Zynq board and it does identify the USB-C port  of the FM191 board and also recognizes it as camera, without any connection from the USB port of EMC2 board to the FM191-U. 

Whereas, when I am running Ubuntu on the board, I need to make the connection from the  USB port of the EMC2 and the FM191-U. The ZED camera is connected through the type-C connector using a USB to USB-C adaptor. Besides, with this connection only USB2.0 is identified and not the USB3.0

**Comment by pedrombmachado** [comment] 2018-07-17 15:40
@timoteogb  and @EmilieWheatley 
Can we please help @Pranjali-Shinde with her question.

**Comment by pedrombmachado** [comment] 2018-07-17 15:48
@Pranjali-Shinde ,
   Please check this [post](https://forums.xilinx.com/t5/General-Technical-Discussion/PCI-Express-x1-amp-USB-3-0-in-Zynq-7020/td-p/680614) and this other (post)[https://www.xilinx.com/products/intellectual-property/1-8dyf-1597.html].

**Comment by pedrombmachado** [comment] 2018-07-17 16:17
@Pranjali-Shinde ,
  The Zed camera works using the USB2. Why don't you work for now with the camera using USB2 and then try to solve the USB3?

**Comment by Pranjali-Shinde** [comment] 2018-07-17 16:38
Hi @timoteogb 
I think the problem is while configuring the petalinux kernel. The physical interface for the Ethernet needs to be selected. The selection comes in the interfaces. The device type in the device tree can be checked if it is ethernet rgmii interface? As it shows some memory addresses, maybe changing the memory setting in the “Subsytem auto hardware setting”  (on the execution of the  petalinux-config command) can be changed.

**Comment by Pranjali-Shinde** [comment] 2018-07-17 16:40
Hi @PedroSundance 
Yes, I am working with USB2 only now. Later I will try with USB3.

**Comment by pedrombmachado** [comment] 2018-07-17 16:41
@Pranjali-Shinde ,
  You need a USB3 core somthing like this [one](https://www.s2i.org/webdownload/Products/FPGA%20Cores/U3V%20Core%20Xilinx/U3V%20Core%20Xilinx.pdf). If not, you will have to write a USB3 core and its drivers. It is a good strategy to start working with the USB2 and then decide how to solve the USB3 issue.

**Comment by Pranjali-Shinde** [comment] 2018-07-17 16:48
Hi @PedroSundance ,
Okay. Thank you for the link. I will try solving the issue of USB3 later as now I am working with USB2.0.
Thank you.

**Comment by pedrombmachado** [comment] 2018-07-17 16:50
Hi @Pranjali-Shinde ,
   You probably just need the USB2 for your application and therefore you might not have to concern at all with the USB3. I am now closing the issue as the problem is now solved.

**Closed by pedrombmachado** 2018-07-17 16:50 UTC
